name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml  # <-- FORCE install
          pip install -r requirements.txt
          pip install .  # if you're using a local package (e.g., with setup.py)

      # Step 4: Confirm YAML is available
      - name: Verify PyYAML installation
        run: |
          python -c "import yaml; print('✅ PyYAML is installed.')"

      # Step 5: Run model evaluation pipeline
      - name: Run model evaluation pipeline
        env:
          MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
          MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_TRACKING_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}
        run: |
          python src/datascience/pipeline/model_evaluation_pipeline.py
