name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8  # Adjust to desired version

    # Step 3: Upgrade pip and install dependencies
    - name: Upgrade pip and install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade -r requirements.txt

    # Step 4: Run tests
    - name: Run tests
      run: |
        pytest tests/

    # Step 5: Lint with flake8 and ignore Python 2-related errors
    - name: Lint code with flake8
      run: |
        pip install flake8
        flake8 . --max-line-length=127 --ignore=F821,F824

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8  # Adjust to desired version

    # Step 3: Deploy model to MLflow
    - name: Deploy model
      env:
        MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
        MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_TRACKING_USERNAME }}
        MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}
      run: |
        python src/datascience/pipeline/model_evaluation.py
